<?php return array(
    'root' => array(
        'name' => 'fchyo/analisiscnn',
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'reference' => NULL,
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'amphp/amp' => array(
            'pretty_version' => 'v2.6.2',
            'version' => '2.6.2.0',
            'reference' => '9d5100cebffa729aaffecd3ad25dc5aeea4f13bb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../amphp/amp',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'amphp/byte-stream' => array(
            'pretty_version' => 'v1.8.1',
            'version' => '1.8.1.0',
            'reference' => 'acbd8002b3536485c997c4e019206b3f10ca15bd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../amphp/byte-stream',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'amphp/parallel' => array(
            'pretty_version' => 'v1.4.3',
            'version' => '1.4.3.0',
            'reference' => '3aac213ba7858566fd83d38ccb85b91b2d652cb0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../amphp/parallel',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'amphp/parser' => array(
            'pretty_version' => 'v1.1.0',
            'version' => '1.1.0.0',
            'reference' => 'ff1de4144726c5dad5fab97f66692ebe8de3e151',
            'type' => 'library',
            'install_path' => __DIR__ . '/../amphp/parser',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'amphp/process' => array(
            'pretty_version' => 'v1.1.4',
            'version' => '1.1.4.0',
            'reference' => '76e9495fd6818b43a20167cb11d8a67f7744ee0f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../amphp/process',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'amphp/serialization' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'reference' => '693e77b2fb0b266c3c7d622317f881de44ae94a1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../amphp/serialization',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'amphp/sync' => array(
            'pretty_version' => 'v1.4.2',
            'version' => '1.4.2.0',
            'reference' => '85ab06764f4f36d63b1356b466df6111cf4b89cf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../amphp/sync',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'andrewdalpino/okbloomer' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => '39321cb515c1e99128d28489b0187120ba7ce84c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../andrewdalpino/okbloomer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ezyang/htmlpurifier' => array(
            'pretty_version' => 'v4.16.0',
            'version' => '4.16.0.0',
            'reference' => '523407fb06eb9e5f3d59889b3978d5bfe94299c8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezyang/htmlpurifier',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'fchyo/analisiscnn' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'reference' => NULL,
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'interop-phpobjects/polite-math' => array(
            'pretty_version' => '1.0.4',
            'version' => '1.0.4.0',
            'reference' => 'b2953499bb20df941df0f1d904e1f1d9a7acd3d4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../interop-phpobjects/polite-math',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'maennchen/zipstream-php' => array(
            'pretty_version' => '2.2.6',
            'version' => '2.2.6.0',
            'reference' => '30ad6f93cf3efe4192bc7a4c9cad11ff8f4f237f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../maennchen/zipstream-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'markbaker/complex' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'reference' => '95c56caa1cf5c766ad6d65b6344b807c1e8405b9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../markbaker/complex',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'markbaker/matrix' => array(
            'pretty_version' => '3.0.1',
            'version' => '3.0.1.0',
            'reference' => '728434227fe21be27ff6d86621a1b13107a2562c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../markbaker/matrix',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'myclabs/php-enum' => array(
            'pretty_version' => '1.8.4',
            'version' => '1.8.4.0',
            'reference' => 'a867478eae49c9f59ece437ae7f9506bfaa27483',
            'type' => 'library',
            'install_path' => __DIR__ . '/../myclabs/php-enum',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'php-ai/php-ml' => array(
            'pretty_version' => '0.9.0',
            'version' => '0.9.0.0',
            'reference' => 'fd8b70629e16ed67307fe150ba25738449b9a6b2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-ai/php-ml',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpoffice/phpspreadsheet' => array(
            'pretty_version' => '1.28.0',
            'version' => '1.28.0.0',
            'reference' => '6e81cf39bbd93ebc3a4e8150444c41e8aa9b769a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpoffice/phpspreadsheet',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-client' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'reference' => '0955afe48220520692d2d09f7ab7e0f93ffd6a31',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-client',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-factory' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'reference' => 'e616d01114759c4c489f93b099585439f795fe35',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.1',
            'version' => '1.1.0.0',
            'reference' => 'cb6ce4845ce34a8ad9e68117c10ee90a29919eba',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '408d5eafb83c57f6365a3ca330ff23aa4a5fa39b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'rindow/rindow-math-matrix' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => '7b23ccd9831b23f898f948e46580114c34d483bb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../rindow/rindow-math-matrix',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'rindow/rindow-math-plot' => array(
            'pretty_version' => '1.0.8',
            'version' => '1.0.8.0',
            'reference' => '7a9f9ea8fa5d693839adec01a09badb554360a69',
            'type' => 'library',
            'install_path' => __DIR__ . '/../rindow/rindow-math-plot',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'rindow/rindow-neuralnetworks' => array(
            'pretty_version' => '1.4.0',
            'version' => '1.4.0.0',
            'reference' => '0ddf191b398f8ed1012504489a069ec7a24b82dd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../rindow/rindow-neuralnetworks',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'rubix/ml' => array(
            'pretty_version' => '2.4.0',
            'version' => '2.4.0.0',
            'reference' => 'e804cdc318801545307ed4a0f3a835fcf22f5864',
            'type' => 'library',
            'install_path' => __DIR__ . '/../rubix/ml',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'rubix/tensor' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '2c5d48498acdc7185819060045c8dc26cd15dd40',
            'type' => 'library',
            'install_path' => __DIR__ . '/../rubix/tensor',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sastrawi/sastrawi' => array(
            'pretty_version' => 'v1.2.0',
            'version' => '1.2.0.0',
            'reference' => '31fd4261dd4980cc57447f44d1aec4bd69e2abec',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sastrawi/sastrawi',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-iconv' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '927013f3aac555983a5059aada98e1907d842695',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-iconv',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-grapheme' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '511a08c03c1960e08a883f4cffcacd219b758354',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-grapheme',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '19bd1e4fcd5b91116f14d8533c57831ed00571b6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '8ad114f6b39e2c98a8b0e3bd907732c207c2b534',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php72' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '869329b1e9894268a8a61dabb69153029b7a8c97',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php72',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '7a6ff3f1959bb01aefccb463a0f2cd3d3d2fd936',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php82' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '80ddf7bfa17ef7b06db4e6d007a95bf584e07b44',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php82',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php83' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '508c652ba3ccf69f8c97f251534f229791b52a57',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php83',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'voku/portable-ascii' => array(
            'pretty_version' => '1.5.6',
            'version' => '1.5.6.0',
            'reference' => '80953678b19901e5165c56752d087fc11526017c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../voku/portable-ascii',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'voku/portable-utf8' => array(
            'pretty_version' => '5.4.51',
            'version' => '5.4.51.0',
            'reference' => '578f5266725dc9880483d24ad0cfb39f8ce170f7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../voku/portable-utf8',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wamania/php-stemmer' => array(
            'pretty_version' => 'v3.0.0',
            'version' => '3.0.0.0',
            'reference' => 'eab7b93465eb3d5da372806c8e1b01da5766aea5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wamania/php-stemmer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
